foqus_lib/gui/solventfit/solventFitSetupFrame.py, test/system_test/ui_test_01.py
Fixed a missing import of QCursor that should fix issue #177.
=> Fixed missing QCursor import.

foqus_lib/framework/sampleResults/results.py
=> Fix string filter

foqus_lib/framework/sampleResults/results.py
=> Fix bool calculates column load and save

foqus_lib/gui/flowsheet/nodePanel.py, foqus_lib/gui/helpers/guiHelpers.py
Don't allow editing of names and do allow numbers starting with "."
This fixes issues #100 and #73
=> Fix editing variable names

foqus_lib/framework/pymodel/heat_integration.py, foqus_lib/framework/pymodel/pymodel_test.py, foqus_lib/framework/pymodel/steam_cycle.py, foqus_lib/framework/surrogate/surrogate.py, foqus_lib/unit_test/nodeVarListTest.py, foqus_lib/unit_test/nodeVarsTest.py
=> Fixed capitalization on NodeVars.

INSTALL.md
This change is to take care of issue #222
=> Added information regarding installing/updating Pandas

foqus_lib/gui/solventfit/solventFitSetupFrame.py
I changed Line 836 in foqus_lib\gui\solventfit\solventFitSetupFrame, so that the changes made for Issue #207 is available in GitHub
=> Changed Line 836 in foqus_lib\gui\solventfit\solventFitSetupFrame

setup.py
This change is also for issue #222
=> Added pandas version requirement for setup.py

INSTALL.md
This change is to take care of some of the problems in Issue #207
=> INSTALL.md: Added instruction for installing R and packages

foqus_lib/framework/sampleResults/results.py, foqus_lib/gui/uq/uqSetupFrame.py
=> Fix for displaying incorrect number of errors in UQ ensemble

foqus.py, foqus_lib/framework/sampleResults/results.py, foqus_lib/gui/uq/uqSetupFrame.py
This should make FOQUS work with the newest versions of pandas without breaking older ones.  
Related to issue #250
=> Fix for pandas problem

foqus_lib/framework/graph/node.py, foqus_lib/framework/sim/turbineLiteDB.py
This is to figure out what is happening to job output when there are errors or warnings from Aspen.
=> Adding logging of turbine job results

README.md
- I added a reference in the README file
- The reference is the Miller et al. (2017) paper, which is a book chapter
=> Added reference to README

README.md
This should take care of Issue #266.
=> README: Added link to PDF version of user's manual

examples/Smoke Tests/fs_smoke_test.py, examples/Smoke Tests/ouu_smoke_test_ex_1.py, examples/Smoke Tests/ouu_smoke_test_ex_2.py, examples/Smoke Tests/ouu_smoke_test_ex_3.py, examples/Smoke Tests/ouu_smoke_test_ex_4.py, examples/Smoke Tests/ouu_smoke_test_ex_5.py, examples/Smoke Tests/ouu_smoke_test_ex_6.py, examples/Smoke Tests/ouu_smoke_test_ex_7.py, examples/Smoke Tests/uq_smoke_test_data_analysis.py, examples/Smoke Tests/uq_smoke_test_data_visualization.py, examples/Smoke Tests/uq_smoke_test_inference.py, examples/Smoke Tests/uq_smoke_test_input_importance.py, examples/Smoke Tests/uq_smoke_test_polynomial.py, examples/Smoke Tests/uq_smoke_test_response_surface_validation.py, examples/Smoke Tests/uq_smoke_test_response_surface_visualization.py, examples/Smoke Tests/uq_smoke_test_response_uq_analysis.py
This fixes issue #271. It gives the longer tests more time to finish and gives the user more feedback in the console about which tests have already completed.
=> Smoke Tests Update

INSTALL.md, manual/FOQUS_User_Manual.tex
Pointing to the releases page and not just the binary to download.
Part of #268
=> Aug release prep

foqus_lib/framework/ouu/OUU.py, foqus_lib/gui/ouu/ouuSetupFrame.py
It works for me now, but I want @fsoepyan to test it.
=> OUU able to handle constraints

foqus_lib/framework/uq/LocalExecutionModule.py
@puttak could you test if this is no longer an issue? Thanks!
=> Fixes issue #263. Error uploading csv files in UQ

foqus_lib/framework/graph/graph.py, foqus_lib/framework/optimizer/optimization.py, foqus_lib/gui/main/mainWindow.py, foqus_lib/gui/uq/uqSetupFrame.py
This should fix the upload flowsheet problem in turbine.
I tested by running a FOQUS consumer on my computer and setting FOQUS to remote with the TurbineLite configuration.  Assuming Turbine and TurbineLite act the same, this should work.
=> Fix optimization using remote turbine.

examples/Smoke Tests/optimization_smoke_test_constraint.py
Added one test to go through constraints. It uses the NLopt solver package. If we need to test constraints on every package please let me know and I will update the other tests.
=> Added Constraint-Based Optimization Test

cloud/aws/node/delete-simulation/package-lock.json, cloud/aws/node/delete-simulation/package.json
changed the dependencies.
https://github.com/CCSI-Toolset/FOQUS/issues/301
=> Lodash fix

README.md
This should take care of issue #259.
=> Update README: Added link for FOQUS installation videos

INSTALL.md
This should take care of issue #259.
=> Update Install.md: Added link for FOQUS installation videos

examples/Smoke Tests/fs_smoke_test.py, foqus_lib/framework/uq/Common.py, foqus_lib/framework/uq/ExperimentalDesign.py, foqus_lib/framework/uq/LocalExecutionModule.py, foqus_lib/framework/uq/Model.py, foqus_lib/framework/uq/SampleData.py, foqus_lib/gui/flowsheet/drawFlowsheet.py, foqus_lib/gui/uq/SimSetup.py
the fs_smoke_test should pass now.
=> Fixed more UQ stuff for Py3

foqus.py
This should take care of Issue #314.
=> Updated foqus.py: Removed QtXml from list of imports

foqus_lib/framework/sampleResults/results.py
=> Added missing line to results.py

foqus_lib/framework/uq/Model.py, foqus_lib/framework/uq/SampleData.py, foqus_lib/gui/uq/RSCombos.py
I've updated a few files so the spin box for MARS degree of interactions pre-populates with the number of variable inputs instead with total number of inputs. This partially fixes issue #313
=> Sotorrio1 #313

foqus_lib/framework/optimizer/problem.py, foqus_lib/gui/optimization/optSampleGenDialog.py, foqus_lib/gui/optimization/optSetupFrame.py
Parent argument was missing from dialog box init function.  Issue #310
=> Fixed optimization generate samples dialog.

foqus_lib/gui/flowsheet/dataBrowserDialog.py
=> Removed question mark icon from corner of data browser dialog

foqus_lib/gui/flowsheet/edgePanel.py
Edge editor fixed.  Issue #377.
=> Fix edge panel

foqus_lib/framework/uq/LocalExecutionModule.py
@sotorrio1 spotted this error in line 314, and after the fix, I can successfully upload a csv file to the UQ module. Thank you!
=> Updated LocalExecutionModule.py, line 314

INSTALL.md
I added the step-by-step installation guide provided by @atowfiq and @sotorrio1.
=> Updated Install.md

foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
takes care of issue #396 (at least partially, SDOE side of things)
=> fixing path name

foqus.py, foqus_lib/gui/sinter/__init__.py, foqus_lib/gui/sinter/sinter_config.py, foqus_lib/gui/sinter/sinter_config.ui, foqus_sinter_configure.py
This is a simple utility to get around the SinterConfigGUI gPROMS parsing problem.
=> Adding a utility to write sinter config files 

foqus_lib/framework/surrogate/ACOSSO.py, foqus_lib/framework/surrogate/ALAMO.py, foqus_lib/framework/surrogate/BSS-ANOVA.py
readline() for subprocess returns bytes now, so updated the code. 
Fixes issue #420
=> Fixing ALAMO, ACOSSO, and BSS-ANOVA for py3.

docs/source/chapt_flowsheet/reference/flowsheet.rst, docs/source/chapt_flowsheet/reference/results.rst, docs/source/chapt_flowsheet/reference/settings.rst, docs/source/chapt_flowsheet/tutorial/data.rst, docs/source/chapt_flowsheet/tutorial/recycle.rst, docs/source/chapt_flowsheet/tutorial/remote.rst, docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst, docs/source/chapt_flowsheet/tutorial/simple_flowsheet.rst, docs/source/chapt_heat/reference.rst, docs/source/chapt_heat/tutorial.rst, docs/source/chapt_opt/reference/optimization.rst, docs/source/chapt_opt/tutorial/parameter_est.rst, docs/source/chapt_opt/tutorial/simple.rst, docs/source/chapt_sinter/tutorial/acm.rst, docs/source/chapt_sinter/tutorial/ap.rst, docs/source/chapt_sinter/tutorial/excel.rst, docs/source/chapt_sinter/tutorial/gproms.rst, docs/source/chapt_surrogates/reference.rst, docs/source/chapt_surrogates/tutorial/acosso.rst, docs/source/chapt_surrogates/tutorial/alamo.rst, docs/source/chapt_surrogates/tutorial/bssanova.rst, docs/source/chapt_surrogates/tutorial/flowsheet.rst, docs/source/chapt_uq/tutorial/sim.rst
Example of the documentation: https://foqus-mine.readthedocs.io/en/latest/
I fixed as many of the internal links as I could.
=> Modified rsts to work with ReadTheDocs

README.md
Changing README.md to use the badge and docs now at RTD.
=> ReadTheDocs for badge and docs

docs/source/chapt_install/index.rst
=> Commented out the install section on git

docs/source/chapt_sdoe/index.rst
Specifically the one mentioned by @sotorrio1 in issue #423 
This is just a temporary change for this Feb release until @candcook can fill it in with forthcoming details.
=> Commenting out an "in progress" paragraph

foqus_lib/framework/surrogate/ALAMO.py
This PR addresses issue https://github.com/CCSI-Toolset/FOQUS/issues/459.
=> Updated citation.

foqus.py, foqus_lib/framework/graph/graph.py, foqus_lib/framework/sim/turbineConfiguration.py, foqus_lib/framework/sim/turbineLiteDB.py
This fixes a few things mostly byte/str problems with FOQUS so that it works correctly with TurbineClient.  The main goal of this is just to get the remote Turbine option working right.
This is related to issue #461, and should enable parallel simulations on a single machine.
=> Fixing some remote tubrine stuff

test/system_test/ui_test_01.py
I modified the test script that is being run on appveyor to be sure the exit code indicated if the tests pass or not. I also tried to clean up the script and make it a bit more reliable.  I think there is a still a good bit of work into making these UI test scripts easier to deal with and  more robust.
=> Test Script Exit Code

foqus_lib/gui/main/mainWindow.py
hiding the basic data tab for now. I suggest after approving this PR, we close issues #176, #207, and #408
=> hiding Basic Data tab

foqus_lib/framework/sampleResults/results.py, foqus_lib/framework/surrogate/surrogate.py, foqus_lib/gui/flowsheet/dataBrowserFrame.py, foqus_lib/gui/flowsheet/edgePanel.py
Fixes issue #456 
I removed the functions to run rows and fixed the rest.
=> Fix data table menu

docs/source/chapt_flowsheet/reference/settings.rst, docs/source/chapt_install/index.rst
=> Replacing en dash with hyphen in command line examples

foqus.py
Addresses #513 
Very simple change of adding the unix "shebang" line at the top of the foqus.py file.
=> Addresses #513 by adding the shebang line

foqus_lib/framework/sdoe/sdoe.py
This should take care of issue #527
=> Adding filename extension to SDOE created designs

foqus_lib/framework/optimizer/BFGS.py, foqus_lib/framework/optimizer/SLSQP.py
This is a correction for issue #529
=> Optimization Solver Message Update

foqus_lib/framework/sdoe/sdoe.py, foqus_lib/gui/common/InputPriorTable.py, foqus_lib/gui/sdoe/SimSetup_UI.ui, foqus_lib/gui/sdoe/sdoeAnalysisDialog.py, foqus_lib/gui/sdoe/sdoeSetupFrame.py, foqus_lib/gui/sdoe/sdoeSimSetup.py
=> Fixing a bug with writing samples created by psuade

foqus_lib/framework/sdoe/sdoe.py
=> Fixing SDoE plotting capability

foqus_lib/gui/sdoe/sdoeSetupFrame.py
There was a bug when deleting rows and trying to save as new ensemble. It should be fixed now
=> Fixing issue #540

foqus_lib/framework/optimizer/problem.py
=> Custom Python Objective function fix

docs/make.bat, docs/source/copyright.rst
This is basically me re/undoing my PRs #502 and #534.
=> Get rid of copyright symlink in pref of using rst include

foqus_lib/gui/optimization/optSetupFrame_UI.ui
Time index is not required for the variables. This correction is made in the description.
=> custom python objective function description change

foqus_lib/gui/uq/uqSetupFrame_UI.ui
The UQ Ensemble information was not completely seen in the GUI earlier. Hence i modified the frame in qt designer.
=> UQ ensemble information frame modified

docs/source/index.rst
Adding list of CCSI2-FOQUS related publications
=> List of Publications

.circleci/config.yml
These are changes to the circleci config file to get it to work using the new v2 workflow structure.
=> Adding CircleCI to FOQUS builds

foqus_lib/framework/foqusOptions/option.py
Pylint motivated fix, addresses #600
=> Missing self ref (pylint discovery)

foqus_lib/framework/solventfit/SolventFit_testing.py, foqus_lib/framework/solventfit/test_solventfit.py
pylint fixes, addresses #600
Should these get run by pytest?
=> pylint fixes in solventfit

.circleci/config.yml, appveyor.yml, docs/source/chapt_install/index.rst
Change to use and suggest python 3.7.5
=> Python 3.7.5

foqus_lib/framework/graph/node.py
It looks like @fsoepyan's log, the log output on line 810 is being printed correctly.  I feel like the problem is not there.  I added logging of the exception I passed on though to help us out.  Related to #639
=> Add logging.

foqus_lib/framework/optimizer/NLopt.py, foqus_lib/gui/optimization/optMonitor.py
This should take care of #593 
I have also attached a simple optimization foqus file, in which the plot changes can be viewed by running the optimization.
=> Optimization Plot Change

docs/source/chapt_sdoe/index.rst
- Adjusting heading levels so that they stay in the SDOE chapter
- Fixing duplicate figure name "fig.3_scatterplot_inputs"
- Fix missing ending of in-line strong at line 304
Part of #638
=> Little SDOE doc fixes

foqus_lib/framework/optimizer/Snobfit.py
import lines  before the try - except block removed
=> snobfit code fix

foqus_lib/framework/uq/LocalExecutionModule.py, foqus_lib/gui/common/InputPriorTable.py
=> Analysis of csv samples in UQ

docs/source/chapt_pyomo/tutorial/pyomo_test.rst
=> Additional changes to foqus pyomo documentation

.circleci/config.yml, docs/Makefile, docs/source/chapt_pyomo/tutorial/pyomo_test.rst
Get CircleCI to build docs and fail if there are any errors (or even warnings).
=> Build docs and check for errors

docs/source/chapt_dev/index.rst, docs/source/chapt_flowsheet/reference/getting_started.rst, docs/source/chapt_install/index.rst, docs/source/chapt_install/install_foqus.rst, docs/source/chapt_install/install_optional.rst, docs/source/chapt_install/install_python.rst, docs/source/chapt_install/run_foqus.rst, docs/source/index.rst
This addressed #701 by updating the install chapter the new install instruction for the PyPi package.  I also broke it out into sections, reformatted a few things here and there.
Also, I added a developer chapter.
The generated result of these should be viewable at: https://lbl-ksbeattiefoqus.readthedocs-hosted.com/en/pip_install_docs/
=> Updates documentation on how to install FOQUS

foqus_lib/gui/flowsheet/drawFlowsheet.py
=> Adding a warning for node name convention

docs/source/chapt_install/run_foqus.rst
Note on packages to install if running on a Linux VM or remote (headless) server.
Rare case, but it's burned me a few times.
=> Note on packages needed when running on a VM

.circleci/config.yml, foqus_lib/foqus.py, foqus_lib/unit_test/test_foqus_main.py, test/test_foqus_main.py
WIP PR addressing the Python side of #795.
=> Add Python tests for command line optimization

foqus_lib/framework/uq/SampleRefiner.py
This should address the missing import found by pylint as described in #815.
=> Add missing PyQt5 import in foqus_lib/framework/uq/SampleRefiner.py

setup.py
Should fix #827.
In `setup.py`:
- Add `*.R` pattern to `package_data`
- Use `find_namespace_packages()` instead of `find_packages()` so that also files inside directories without `__init__.py` are included as well
=> Ensure that all R files are installed

foqus_lib/framework/sdoe/nusf.py
Convert NUSF dataframe code to numpy to speed it up. Addresses issue #766
=> NUSF "numpyfication"

foqus_lib/framework/session/session.py, foqus_lib/framework/sim/turbineConfiguration.py, foqus_lib/gui/help/helpBrowser.py, foqus_lib/gui/help/helpBrowser_UI.ui
Add default turbine_aws.cfg and status button for Cloud Log
#866
=> Turbine AWS Configuration and Status Update

foqus_lib/framework/optimizer/SM_Optimizer.py
This should take care of #897 
I tested a tutorial example and it works fine.
=> Removing import statement from SM_Optimizer.py

docs/source/chapt_debug/index.rst
Addresses issue #880.
We should probably run down the list of know issues at the next meeting.  I'm not really up-to-date anymore, so I don't really know what's current.  I removed one issue related to the old py2exe installer, and added the Aspen Plus issue with Excel calculator blocks.
=> Update known issues

docs/source/chapt_surrogates/reference.rst
=> Documenting a note on calculated variables for surrogates

docs/source/chapt_odoe/reference.rst
Updating ODoE documentation with overview section
=> update ODoE documentation

docs/source/chapt_ouu/reference.rst
@ngbrenda found a few typos in the OUU documentation
=> update OUU reference documentation

foqus_lib/framework/uq/LocalExecutionModule.py, foqus_lib/gui/sdoe/sdoeSetupFrame.py
Handling the pop up window differently and only showing up when there is any missing data. Should take care of issue #977
=> Fixing issue #977

foqus_lib/framework/sdoe/nusf.py
=> Fix NUSF with history

foqus_lib/foqus.py, foqus_lib/framework/listen/listen.py, foqus_lib/gui/optimization/optMonitor.py, foqus_lib/gui/surrogate/surrogateFrame.py, foqus_lib/gui/uq/uqSetupFrame.py, foqus_lib/service/flowsheet.py
should take care of issue #1000
=> addressing python3 API change from isAlive to is_alive

foqus_lib/framework/sdoe/nusf.py, foqus_lib/framework/sdoe/plot_utils.py
SDoE scatterplot enhancements to improve usability and assessment of design coverage/properties.
-Plots (N)USF candidate, design, and previous points and in different styles.
-Reweights transparency of candidate points by a specified weight.
=> Sdoe plot update

setup.py
- Update TurbineClient to version 4.0.2 now that PyPI package is available
- Update `TurbineClient` requirement to 4.0.2
=> Update TurbineClient to 4.0.2

setup.py
Now that a Conda package for PyQt 5.15 exists, we can update (from the current 5.12) to see if this is enough to resolve the problems described in #1064.
- Update PyQt requirement to 5.15
=> Update PyQt to 5.15

docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst, docs/source/chapt_install/install_optional.rst
Clarifies usage of Turbine and SimSinter in installation instructions, and adds a link to the relevant tutorial page.
- Small changes to documentation pages
=> Add Optional Software Install and Tutorial Notes

docs/source/chapt_install/install_optional.rst
=> Fix broken link in Install Optional Software docs

foqus_lib/framework/sim/turbineConfiguration.py
This exception handling code was throwing an exception because the attribute being checked was not present.
When looking to reproduce issue #1114 ran into this code throwing an exception.
- checking to see if attribute is present on object
=> adding attribute check to avoid throwing exception

foqus_lib/gui/main/mainWindow.py
#1114 
#1114 
- updates the error dialog to always include "For more details see the Log Viewer in Help." as additional guidance for the user.
=> added call out to look at the Log Viewer in Help for more details

foqus_lib/framework/sdoe/df_utils.py, foqus_lib/framework/sdoe/distance.py, foqus_lib/framework/sdoe/irsf.py, foqus_lib/framework/sdoe/nusf.py, foqus_lib/framework/sdoe/plot_utils.py, foqus_lib/framework/sdoe/sdoe.py, foqus_lib/framework/sdoe/usf.py, foqus_lib/framework/session/session.py
Addresses issue #1111 
Adding type annotations to all SDoE files
- adding SDoE type annotations
- adding some function descriptions 
=> Adding type annotations to SDoE

foqus_lib/framework/sdoe/sdoe.py
https://github.com/orgs/CCSI-Toolset/discussions/1213#discussioncomment-8953817
- Convert logging exception to warning on Dask get_client() failure
=> Convert logging exception to warning on Dask get_client() failure

docs/source/chapt_flowsheet/reference/settings.rst, docs/source/chapt_install/install_optional.rst, docs/source/chapt_surrogates/tutorial/alamo.rst
Add notes pointing out that ALAMO can have two executables and indicating the correct executable to add to the Settings path.
=> Update Docs For ALAMO EXE Note

docs/source/chapt_install/install_optional.rst, foqus_lib/framework/surrogate/ACOSSO.py, foqus_lib/framework/surrogate/BSS-ANOVA.py
=> update docs for SimSinter and TurbineLite configuration to clarify path locations

.readthedocs.yaml, foqus_lib/framework/graph/graph.py, foqus_lib/framework/optimizer/NLopt.py, foqus_lib/framework/optimizer/SM_Optimizer.py, foqus_lib/framework/optimizer/Snobfit.py, foqus_lib/framework/optimizer/problem.py, foqus_lib/framework/sampleResults/results.py, foqus_lib/framework/uq/flowsheetToUQModel.py, foqus_lib/gui/help/helpBrowser.py, foqus_lib/gui/ouu/nodeToUQModel.py, foqus_lib/gui/uq/uqSetupFrame.py
The typos-cli package has been updated, so there are new typos to fix.  Also readthedocs now wants an explicit path to the conf.py file.
- Fixing all the new typos
- Adding in the path to the RTD config file
=> Fixes for typos update and RTD config
