- foqus_lib/gui/flowsheet/dataBrowserFrame.py
Fixes issue #208.  Just fixed the row count not appearing. Don't want to default filter to all because there is a chance it may not exist.
> Fixed missing row count when filter box is first opened.

- INSTALL.md
- examples/Smoke Tests/README.md
- foqus_env_ssh.yml
- setup.py
- test/auto_test/README.md
- test/auto_test/foqus_setup_ssh.sh
I've modified the setup file to accept an ssh option allowing the user to easily switch to ssh if desired. If no additional options are included the setup defaults to https (normal behavior). With this change I've edited the install documentation to include instructions for how to use this option.
I've added readme files for the smoke tests and the testing scripts and an ssh version of the setup script that incorporates this option.
This should solve #161
> SSH Option and Readme Files for Tests

- foqus_lib/framework/graph/node.py
Since the type defaults to float, string variables would run into problems setting values from the sinter cofig.
> Fix failing to read input var data type from simsinter

- INSTALL.md
This was linking to an old release.  The docs may not have changed since then, but linking this way will point people to the latest release, in the even the docs do change!
Also, does a user really need to download the zip file, then copy the contents into a subdir to get the on-line docs?  That seems like something that could be made easier.
> Small correction on how to get the online docs

- foqus_lib/framework/sampleResults/results.py
- foqus_lib/gui/flowsheet/dataFilterDialog.py
- foqus_lib/gui/flowsheet/dataFilterDialog_UI.ui
This is an update to make filtering easier to understand.  We will need to update the documentation at some point though.  This could break some of @CSRussell2319's tests if there are filter tests.
This is related to issue #312 
The box for a filter now takes a Python expression.  This expression should return a numpy array or list that has the same number of elements as rows in the data table where each entry is true or false.  True to include a row false to exclude it.  The syntax is the same as calculated columns.  There is a c("my_column") function that returns a numpy array of values in my_column. You can write your Python expression how you want, but I recommend numpy logic functions https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.logic.html.  Numpy is imported as np. …
> Change Filter Method to Use Calculated Columns

- INSTALL.md
- foqus_lib/framework/sim/turbineLiteDB.py
- requirments.txt
- setup.py
I added requirements.txt which I hope will fix the weird import errors that we were getting with requirements installed from setup.py.  Installing those added a step to the install instructions.
I also took a shot at generating a batch file on windows at the end of setup.py.  It works good for me, but several people will probably need to try it to ensure it works for different setups.  I think as long as it looks reasonable it's probably fine to merge then test.
I also dropped the enumerated type value that was causing problems  with adodbapi.  I don't know why sometimes the enum is there sometimes and not others.  Maybe if has something to do with where you get your pacakages, but I replaced it with the number to avoid problems.
@boverhof, I added python-dateutil==2.5.0 to requirements …
> Batch File and requirements.txt

- foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
Small change in the datetime format to create directories since it was causing some issues in Windows OS. Should take care of issue #378
> fixing issue with creating directories in Windows OS

- docs/make.bat
This just adds a make.bat script, which seems to be the standard way to build sphinx docs on windows.  
Built docs are in: docs/build/html/index.html
@fsoepyan, once this is in, would you make sure you can build the docs and give them a read through and see if you can pick out what needs to be updated.  There are also some possible problems with references and enumerated lists from the conversion too we'll need to look out for.
> Adding a new sphinx make.bat file for windows.

- docs/source/chapt_flowsheet/reference/results.rst
- docs/source/chapt_install/index.rst
- docs/source/index.rst
- foqus_lib/gui/main/mainWindow.py
Adding install docs to sphinx manual.  Eventually I want to add an a reference to the install docs i the readme and remove install.md.  In the sphinx docs it will be easier to create separate pages for different installation methods.   
We have a few install paths and maybe it would be easier to write more specific instructions for each
* Anaconda vs no anaconda
* conda yml environment set up vs pip install all requirements
* User vs developer.
> Add install instructions to sphinx docs.

- setup.py
Fix issue #430.  Here is whats in this:
- fixes the quotes in the foqus.bat files to protect against spaces in paths
- uses the full Python path to avoid other potential problems
- added SimSinter to the optional software in the end messages of setup.py.
- added a short description of each optional package.
> Fix bat quotes

- foqus_lib/gui/sinter/sinter_config.py
This just clears some rows in tables that should be empty when the gPROMS sinterconfig gui starts.  I haven't reproduced this, but I saw the inputs-table seemingly start with a couple blank rows for someone else.  This may not fix anything, but at least this PR won't hurt anything.
> Clear tables in init in case there are some extra rows in the ui file.

- docs/source/chapt_flowsheet/reference/flowsheet.rst
- docs/source/chapt_flowsheet/reference/results.rst
- docs/source/chapt_flowsheet/reference/settings.rst
- docs/source/chapt_flowsheet/tutorial/data.rst
- docs/source/chapt_flowsheet/tutorial/recycle.rst
- docs/source/chapt_flowsheet/tutorial/remote.rst
- docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst
- docs/source/chapt_flowsheet/tutorial/simple_flowsheet.rst
- docs/source/chapt_heat/reference.rst
- docs/source/chapt_heat/tutorial.rst
- docs/source/chapt_opt/reference/optimization.rst
- docs/source/chapt_opt/tutorial/parameter_est.rst
- docs/source/chapt_opt/tutorial/simple.rst
- docs/source/chapt_sdoe/index.rst
- docs/source/chapt_sinter/tutorial/acm.rst
- docs/source/chapt_sinter/tutorial/ap.rst
- docs/source/chapt_sinter/tutorial/excel.rst
- docs/source/chapt_sinter/tutorial/gproms.rst
- docs/source/chapt_surrogates/reference.rst
- docs/source/chapt_surrogates/tutorial/acosso.rst
- docs/source/chapt_surrogates/tutorial/alamo.rst
- docs/source/chapt_surrogates/tutorial/bssanova.rst
- docs/source/chapt_surrogates/tutorial/flowsheet.rst
- docs/source/chapt_uq/tutorial/sim.rst
These warnings will still come up:
docs/source/chapt_sdoe/index.rst:106: WARNING: image file not readable: chapt_sdoe/figs/4_scatterplot_aggregated.png                                                                                                                                                                                       
docs/source/chapt_flowsheet/tutorial/remote.rst:80: WARNING: undefined label: overview.turbine.upload (if the link has no caption the label must precede a section header)
docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst:64: WARNING: undefined label: chapt.simsinter (if the link has no caption the label must precede a section header)
docs/source/chapt_flowsheet/tutorial/simple_flowsheet.rst:12: WARNING: undefined label: sec.flowsheet.starting.foqus (if …
> Fixing make html warnings.

- foqus_lib/framework/optimizer/BFGS.py
- foqus_lib/framework/optimizer/NLopt.py
- foqus_lib/framework/optimizer/OptCMA.py
- foqus_lib/framework/optimizer/PSUADE.py
- foqus_lib/framework/optimizer/SLSQP.py
- foqus_lib/framework/optimizer/Sample.py
- foqus_lib/framework/plugins/pluginSearch.py
- foqus_lib/framework/surrogate/ACOSSO.py
- foqus_lib/framework/surrogate/ALAMO.py
- foqus_lib/framework/surrogate/BSS-ANOVA.py
This fixes issue #462 
Added try/except and logging for finding future problems.   The problem was a 0x90 in ACOSSO.py.  I don't know how it got there, but I changed the plugin search code to read the files with UTF-8 encoding.  That fixed it.  That character must have gotten in recently somehow.
> Fix plugin search

- foqus_lib/framework/graph/heatIntegration.py
This addresses #453 by reindenting the file using `autopep8 --select E11 heatIntegration.py`
This should be white-space only changes, but I'm not entirely sure if or how we can test this as it appears to generate a GAMS file which we can run since we don't have a GAMS license.
> Fixing taberror and reindenting heatIntegration.py

- foqus_lib/framework/surrogate/ALAMO.py
- foqus_lib/framework/surrogate/foqusALAMOClient.py
- foqus_lib/gui/surrogate/surrogateFrame.py
- foqus_lib/gui/surrogate/surrogateFrame_UI.ui
This relates to issue #482.  I don't think we should ask users to mess with the registry or file associations in Windows.  So I came up with a solution that is not great, but at least doesn't require any crazy setup.  This is that same situation faced by @sotorrio1 for the py file called by psuade.  I just spit out a bat script that contains "python wathever\path\whatever.py %*".  This will just use the python in the environment to run the script.  No registry modification needed.  Unless anyone has a better solution, I suggest the same for the psuade counter part, and we try to keep the install simple.  In this case the the bat is needed because ALAMO expects a single file to execute and doesn't understand "python path\to\file.py"
The other change in this is to give you an error that you …
> ALAMO Adaptive sampling fix.

- docs/source/copyright.rst
This is just fixing the link for the copyright.rst file.  Hopefully this will still work on Windows...
> Fixing link for copyright.rst file

- docs/make.bat
Copy over symlinks with contents of LICENSE.md file during sphinx run.  Restores symlink afterward to git doesn't know any better.
> Update make.bat to handle symlink

- foqus_lib/framework/uq/ResponseSurfaces.py
scipy.misc.comb is deprecated in scipy 1.0.0. Using scipy.special.comb instead.
This should take care of issue #545
> Fixing UQ bug related to scipy deprecation

- .circleci/config.yml
- README.md
I thought there was an issue about getting tests going again, but it appears there isn't one.
This should add a very simple but working "proof-of-concept" of CircleCI running pytest and generating a coverage report.
> Adding pytest & coverage via CircleCi

- docs/source/chapt_surrogates/tutorial/alamo.rst
When generating the docs, I'm seeing the following warning:
/home/ksb/Projects/CCSI/github/ksbeattie/FOQUS/docs/source/chapt_surrogates/tutorial/alamo.rst:184: WARNING: undefined label: fig.tut.sur.datafilter (if the link has no caption the label must precede a section header)
I think this fixes it, but I'm not entirely sure.
> Fixing reference in alamo tutorial

- docs/source/chapt_uq/tutorial/data.rst
Again, more of my attempts to make doc generation warnings go away...
I was getting this:
```
/home/ksb/Projects/CCSI/github/ksbeattie/FOQUS/docs/source/chapt_uq/tutorial/data.rst:54: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ksb/Projects/CCSI/github/ksbeattie/FOQUS/docs/source/chapt_uq/tutorial/data.rst:66: WARNING: Error in "figure" directive:
invalid option block.
.. figure:: ../figs/tutorial/12_FilterResults2.png
:alt: Data Manipulation, Filtering Results
Data Manipulation, Filtering Results
```
This PR has several changes in it, all in an attempt to clean things up.  Nothing was deleted, just moved around a little bit.
Please review for correctness.
> fix warnings in UQ data tutorial docs

- docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst
The following warnings come up when generating the docs:
```
/home/ksb/Projects/CCSI/github/ksbeattie/FOQUS/docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst:117: WARNING: undefined label: fig.tut.opt.nodeeditor (if the link has no caption the label must precede a section header)
/home/ksb/Projects/CCSI/github/ksbeattie/FOQUS/docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst:127: WARNING: undefined label: fig.tut.opt.nodeeditor (if the link has no caption the label must precede a section header)
```
This is an attempt to fix them, but I'm not 100% I've done it correctly.
While doing this I noticed another problem at line 52 of sim_flowsheet.rst:  Should it start with a `[subsec.opt.tutorial.flowsheet]`?
> Fix doc warnings in sim_flowsheet.rst

- requirements.txt
The automated tests were failing because a new version of `sip` was released that is incompatible with PyQt5 5.9.
This message came when running `pip install -r requirements.txt`:
ERROR: pyqt5 5.9 has requirement sip<4.20,>=4.19.3, but you'll have sip 5.0.0 which is incompatible.
This patch fixes the version of `sip` to `4.19.8` (the most recent with a pypi package) yet less than `5.0`
Now, I'm not entirely sure this is the correct version of sip to use.  https://www.riverbankcomputing.com/software/sip/download seems to suggest that the package `PyQt5-sip` should be used, which when I checked brings in version `12.7.0` which seems entirely different.
Any ideas on which version of `sip` we should be using?
> Fixing sip to latest version compatable with PyQt5 5.9

- foqus_lib/framework/foqusException/foqusException.py
pylint discovery, addresses #600 
```
************* Module foqus_lib.framework.foqusException.foqusException
foqus_lib/framework/foqusException/foqusException.py:35:8: E1121: Too many positional arguments for method call (too-many-function-args)
foqus_lib/framework/foqusException/foqusException.py:44:4: E0211: Method has no argument (no-method-argument)
```
Looks like a missing `self`.
> missing "self" in func defn

- foqus_lib/framework/at_dict/at_dict.py
Addresses #600
```
************* Module foqus_lib.framework.at_dict.at_dict
foqus_lib/framework/at_dict/at_dict.py:15:8: E1003: Bad first argument 'AtDict' given to super() (bad-super-call)
foqus_lib/framework/at_dict/at_dict.py:20:8: E1003: Bad first argument 'AtDict' given to super() (bad-super-call)
foqus_lib/framework/at_dict/at_dict.py:26:8: E1003: Bad first argument 'AtDict' given to super() (bad-super-call)
```
Fixed based on python 3 suggestion here:
https://docs.quantifiedcode.com/python-anti-patterns/correctness/bad_first_argument_given_to_super.html
> pylint errors in at_dict: bad super() call

- foqus_lib/unit_test/massBalanceTest.py
- foqus_lib/unit_test/nodeVarListTest.py
- foqus_lib/unit_test/nodeVarsTest.py
First step for #600 
I've changed the cases of a few classes so that `pylint -E foqus_lib/unit_test` passes.
> Fixing cases in unit_test so pylint -E passes

- foqus_lib/framework/graph/OptGraphOptim.py
- foqus_lib/framework/graph/graph.py
- foqus_lib/framework/graph/heatIntegration.py
- foqus_lib/framework/graph/nodeVars.py
Addresses #600 
Not 100% sure I fixed the "base raise" statement correctly, please review...
```
************* Module foqus_lib.framework.graph.graph
foqus_lib/framework/graph/graph.py:1350:12: E0704: The raise statement is not inside an except clause (misplaced-bare-raise)
************* Module foqus_lib.framework.graph.heatIntegration
foqus_lib/framework/graph/heatIntegration.py:10:26: E1101: Module 'foqus_lib.framework.graph.node' has no 'nodeVars' member; maybe 'NodeVars'? (no-member)
foqus_lib/framework/graph/heatIntegration.py:17:30: E1101: Module 'foqus_lib.framework.graph.node' has no 'nodeVars' member; maybe 'NodeVars'? (no-member)
foqus_lib/framework/graph/heatIntegration.py:24:31: E1101: Module 'foqus_lib.framework.graph.node' has no 'nodeVars' member; maybe 'NodeVars'? …
```
> Pylint errors in framework/graph/

- requirements.txt
Addresses #679 by downgrading pandas
This should be addressed by [moving to the new API](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html#backwards-incompatible-api-changes) with the 1.0 release of panda.
> Downgrade pandas to 0.25.3

- foqus_lib/framework/uq/LocalExecutionModule.py
These lines of code give an error while viewing and analyzing csv files with 3 input variables. I tried to remove these lines, and its possible to upload, view, and analyze the csv samples without them. I have checked it with a few csv files. It would be helpful if someone else could verify this too.
> Upoading csv samples to UQ tab - revised code

- docs/source/chapt_pyomo/tutorial/pyomo_test.rst
Related to #669 and #694 
When generating the docs there were several errors:
./docs/source/chapt_pyomo/tutorial/pyomo_test.rst:35: WARNING: Bullet list ends without a blank line; unexpected unindent.
./docs/source/chapt_pyomo/tutorial/pyomo_test.rst:35: WARNING: Inline emphasis start-string without end-string.
./docs/source/chapt_pyomo/tutorial/pyomo_test.rst:35: WARNING: Inline emphasis start-string without end-string.
...
Which resulted in some broken layout, which can be seen (before this PR is merged) [here](https://foqus.readthedocs.io/en/latest/chapt_pyomo/tutorial/pyomo_test.html).
These changes fix those errors and attempts to improve the layout and readability of the page.
Please look over the changes I've made here and how they are rendered (`cd docs`, `make clean html` then …
> Fix some sphix errors and improve layout

- .circleci/config.yml
- .gitignore
- appveyor.yml
- docs/Makefile
- docs/source/chapt_debug/index.rst
- foqus_lib/version/version.template
- requirements-dev.txt
- requirements.txt
- setup.py
Changes so that a pypi package can be created.
There's a few changes here to where requirements live and how to setup a developers env.
Regular "end-user" requirements now live in `setup.py` in the `install_requires` list.  They should **_not_** live in `requirements.txt` anymore.  All that's left in `requirements.txt` now (beyond comments) is the line `-e .` which means "look in setup.py".
I've also moved "developer" requirements into a new `requirements-dev.txt` file so that people who don't want those can not bother with them.
This changes (a little) how a developer setup up their environment.  The new instructions are (I will put these in the docs, but here they are for now):
1. Create a new conda env (here named "foqus")
```
conda deactivate
conda remove --name foqus --all
conda …
```
> pip install ccsi-foqus

- foqus_lib/foqus.py
I've re-worked the PyQt5 imports so that with one global "PyQt5" all the "undefined-variables" errors go away.
There's probably a better way to do this, say for example using a class with "PyQt5" be a member var, though that would be a larger refactor than I'm able to take on right now.  Still, please review if this change makes sense.
This still leaves pylint errors:
```
$ pylint -E foqus_lib/foqus.py
************* Module foqus_lib.foqus
foqus_lib/foqus.py:455:14: E1101: Instance of 'plugins' has no 'optimizers' member (no-member)
foqus_lib/foqus.py:455:41: E1101: Instance of 'plugins' has no 'current' member (no-member)
```
which I'm not sure how to test, so I didn't try changing anything.
This does bring up another question: could we have a canned test to run an optimization problem …
> Pylint fixes for foqus_lib/foqus.py

- .circleci/config.yml
- appveyor.yml
Adding `scipy.spatial` to ignored modules list as it contains C functions.
This came up when looking at pylint errors in `foqus_lib/framework/ouu/OUU.py`
Part of #600
> pylint should ignore scipy.spatial

- .circleci/config.yml
- appveyor.yml
This addresses the first part of #795:
Add the command line test of foqus to our CI systems:
foqus --load ./examples/test_files/Optimization/Opt_Test_01.foqus --run opt --out test_opt.foqus
Add to both appveyor and circleci
> Add foqus cmd line test

- .circleci/config.yml
- .pylint/foqus_transform.py
- .pylint/pylintrc
- foqus_lib/framework/optimizer/problem.py
- requirements-dev.txt
This PR implements changes aimed at getting rid of false-positive errors, i.e. portions of the codebase that are erroneously interpreted as errors by the pylint static analysis.
This is part of the efforts towards addressing #600. Specifically, this PR contains only changes that affect pylint exclusively, and thus **do not alter** the runtime behavior of the code in any way, i.e.:
- pylint configuration
- pylint commands in the CI configuration
- pylint directives expressed as comments throughout the codebase
The idea is to keep those sets of changes that do affect the code itself (and that therefore could alter the runtime behavior) in dedicated PRs, to streamline both the fixes and the review process. In other words, reviews for this PR can concentrate entirely on the pylint analysis, …
> Pylint-specific configuration and directives to address false-positive errors

- foqus_lib/framework/listen/listen.py
This should be a straightforward fix for the missing import caught by pylint described in #807.
> pylint: add missing import

- foqus_lib/framework/uq/Model.py
Part of the efforts towards #600.
These errors are false positives, in the sense that the code works, but the slightly unusual syntax seems to annoy pylint. The changes in this PR are a possible solution for using a more idiomatic syntax that also manages to make pylint happy.
> Refactor method args to get rid of pylint false-positive errors

- .circleci/config.yml
- foqus_lib/foqus.py
- foqus_lib/unit_test/test_foqus_main.py
- pytest.ini
This PR addresses PyQt5 errors occurring when invoking `foqus` in GUI mode as described e.g. in #821. Although it was not possible to reproduce the error consistently, the cause seems to be related to the way PyQt5 modules are imported in `foqus_lib.foqus`. This PR adds an explicit import of the required PyQt5 modules in the `guiImport()` function, to make sure that they're properly initialized when the GUI objects are instantiated.
In addition to the changes to the code, I added two tests. Although the conditions under which the original error occurs aren't known precisely, the tests will fail in similar circumstances.
1. Check that it's possible to create a `QApplication` instance after running the `foqus_lib.foqus.guiImport()` function
1. Test that the actual FOQUS GUI window is …
> Address PyQt-related errors when initializing GUI in foqus_lib.foqus

- foqus_lib/gui/model/dmfUploadDialog.py
This PR is part of the ongoing effort for addressing pylint false-positive errors towards #600.
In this case, the imports within the import guard for `dmf_lib` (`try import ... ; except:`) are reported as `import-error`s by pylint, even though the possible missing import is dealt with correctly at runtime.
The changes in this PR are almost completely pylint-specific: the only modification to the runtime behavior is to use a more specific exception type in the `except` clause, as this is usually the preferred way to implement this type of functionality.
> Make import guard for dmf_lib more specific and disable pylint import-error check

- foqus_lib/framework/optimizer/SM_Optimizer.py
The log and exp functions are used from pyomo imports. With the change in pyomo environ import style, these additional imports are required.
> Add more imports for surrogate modeling

- setup.py
- In #832 we switched from `find_packages()` to `find_namespace_packages()`in `setup.py`. This allows non-Python files to be installed without having to create a `__init__.py` file in the directory where they are located
- However, this had the unintended consequence of directories other than `foqus_lib`, such as `examples/` and `cloud/`, to be included in the in the Python distribution package, which in turn resulted in multiple errors showing up in e.g. CI checks
- Moreover, even though it would be possible to address these particular issues, our use case falls outside of the primary use case for `find_namespace_packages()`, which is to create multi-distribution packages (i.e. Python packages that are distributed and installed separately, but operate as a single package at runtime)
- …
> Revert to find_packages() to find packages

- .circleci/config.yml
- .pylint/pylintrc
- foqus_lib/framework/graph/node.py
- foqus_lib/framework/optimizer/optimization.py
- foqus_lib/framework/sampleResults/test/results_s3_test.py
- foqus_lib/framework/sdoe/sdoe.py
- foqus_lib/framework/sim/turbineConfiguration.py
- foqus_lib/framework/surrogate/surrogate.py
- foqus_lib/framework/uq/LocalExecutionModule.py
- foqus_lib/framework/uq/Plotter.py
- foqus_lib/gui/flowsheet/dataBrowserFrame.py
- foqus_lib/gui/flowsheet/runRowsDialog.py
- foqus_lib/gui/heatIntegration/heatIntegrationFrame.py
- foqus_lib/gui/help/helpBrowser.py
- foqus_lib/gui/main/mainWindow.py
- foqus_lib/gui/ouu/foqusPSUADEClient.py
- foqus_lib/gui/ouu/ouuSetupFrame.py
- foqus_lib/gui/sdoe/sdoeSetupFrame.py
- foqus_lib/gui/sdoe/sdoeSimSetup.py
- foqus_lib/gui/uq/SimSetup.py
- foqus_lib/gui/uq/uqSetupFrame.py
- foqus_lib/service/flowsheet.py
- The changes in this PR address all remaining pylint errors, and switches on the actual pylint check in CircleCI
- This does not include the errors in #812 being addressed in #862 (i.e. we need to merge in #862 to have zero pylint errors on the whole codebase)
- The fixes address both false positives (functioning code mistakenly flagged as error by pylint) and true positives (pylint errors that would cause actual errors at runtime)
- Some fixes for true positives silence the pylint error but do not address the error itself; these are marked with `# TODO pylint: disable=...` (as opposed to the standard `# pylint: disable=...`
> pylint fixes home stretch

- docs/source/_static/schema.css
This should stop (most of) the images in the docs from being resized (on large monitors) as described in PR #889 
Regardless, I think it looks better to use the full width of the browser screen for displaying docs, though I'd like _others to review how this looks_ as it changes **EVERY PAGE** of our docs!
I also just added to all PRs (via a change to the RTDs config) that the docs are built for that PR and a link to that is below as part of all the other tests that are run.
> Get RTDs to use full width of page

- docs/source/chapt_debug/index.rst
- docs/source/chapt_dev/index.rst
- docs/source/contact.rst
- docs/source/index.rst
This addresse #771 by creating a new contact page and including it in the top index and in the debug and developer chapters.
> Better contact info in docs

- .readthedocs.yaml
- docs/Makefile
This is a small change so that ReadTheDocs will fail if there are any warnings found when generating our documentation.
Adding a .readthedocs.yaml file to set a config option for RTDs to fail if there are any warnings when generating the documentation.  Adding a similar change to the Makefile so the same happens when building the docs locally.
> Make warnings failures for ReadTheDocs builds

- foqus_lib/framework/optimizer/SM_Optimizer.py
- pyomo is an optional dependency for the `SM_Optimizer` plugin, but unlike other plugins, the message reporting the unavailability of plugin dependencies is logged as an error
- This causes a false-positive error (FOQUS doesn't crash), which could nonetheless cause some tests to fail (e.g. if the tests look at log output to check for `ERROR` messages) in addition to being confusing
- Use `logger.info()` instead of `logger.exception()` to display error message
> Use INFO level if failing to import optional pyomo dependency in SM_Optimizer plugin

- .github/workflows/checks.yml
- .github/workflows/tests.yml
- Enable more readable, "abstract" names for OSes in job matrix (e.g. `linux` instead of `ubuntu-20.04`)
- Mostly done to have a shorter, more memorable name instead of the OS specifiers required by GitHub
- This has the added advantage that the "concrete" OS specifiers can be changed without having to update the name in the "Settings > Branch protection > Required checks" panel for the repository
- Use more general name for complete workflow ("Checks" instead of "Tests")
> Improve naming for GitHub Actions workflows and jobs

- .github/actions/setup-foqus/action.yml
- .github/workflows/checks.yml
- The `build-docs` and `pylint` jobs fail due to repeated timeouts/network errors at the `pip install` stage
- This seems to be due to a failure in pip's dependency solver, causing pip to download multiple versions of the same package from PyPI in rapid succession, leading to the network errors
- The failing jobs were seen in e.g. #916, but most likely they're unrelated to the PR's content
- Possibly, but not obviously, related to pip-related errors such as e.g. IDAES/idaes-pse#439
- Adopt the same Conda-based strategy already in use for the `pytest` job to setup the environment for the `build-docs` and `pylint` jobs
> Address CI failures due to pip install job timeouts

- foqus_lib/framework/uq/Plotter.py
- Identity comparisons with literals (`a is 1` as opposed to `a == 1`) cause a `SyntaxWarning` in Python 3.8
- This PR addresses two such cases as reported by @anujad95
> Address SyntaxWarnings in Python 3.8

- requirements-dev.txt
- The PyPI package `coveragepy` (as opposed to the "Coverage.py" package, which is named `coverage` on PyPI) is most likely not needed, and may result in some installation incompatibilities as reported by @anujad95
> Remove unneeded coveragepy package

- .readthedocs.yaml
- docs/source/conf.py
The project name, used only in the LaTeX / PDF output from ReadTheDocs was "CCIS" and not "CCSI".  This fixes that typo.
This PR also adds to `.readthedocs.yaml` the directive to build all formats of the docs.  It seems we stopped building the PDF versions when that `.readthedocs.yaml` file was first introduced (leaving 3.9.0, as the latest release with PDF docs).  Unfortunately RTD does not produce the PDF format when building for a PR, so we'll have to merge this to see if it works or not.
> Fixing typo in LaTeX / PDF project name

- foqus_lib/framework/sdoe/irsf.py
- foqus_lib/framework/sdoe/plot_utils.py
There was an issue in IRSF that was applying the reverse scaling function twice, hence the final values were way out of range and the design points weren't showing up in the plot. This should take care of issue #948
> Fixing bug in IRSF

- docs/source/chapt_surrogates/tutorial/uq_model.rst
This should take care of #846 
It is something the users must take note of, while opening a FOQUS file containing the response surface validation results in the UQ module. This note has been added to the appropriate tutorial.
> SM UQ Plugin Tutorial

- README.md
The link was wrong.
(This might need to be done for all the other products in the CCSI-Toolset org...)
> Fixing link to contributors

- foqus_lib/gui/sdoe/sdoeSetupFrame.py
Depending on the existence of missing values in the uploaded candidate set, the columns in the **Design Setup** table will show/hide dynamically to avoid user confusion. Should take care of issue #993, suggested by @sspoon
> SDoE: Show/hide table columns dynamically

- .github/actions/setup-foqus/action.yml
- .github/workflows/nightlies.yml
- docs/source/chapt_install/install_optional.rst
After the release of LLNL/psuade-lite 1.9, the Conda packages for 1.9 are available on the CCSI-Toolset Anaconda channel. However, psuade-lite 1.9 won't be compatible with FOQUS until #980 is merged, so, in the meantime, I've added a version specifier whenever psuade-lite is installed so that the compatible version is used. Until this PR is merged, tests might start failing (including the nightly builds), therefore I've marked this as high priority.
Once this PR is merged in, @sotorrio1 can test that this works as expected with #980:
> Pin psuade-lite to 1.8 version before #980 is merged

- foqus_lib/gui/flowsheet/dataBrowserFrame.py
> FOQUS Cloud: fixing OUU bug

- .github/actions/setup-foqus/action.yml
- .github/workflows/checks.yml
- .github/workflows/nightlies.yml
- docs/source/chapt_dev/index.rst
- docs/source/chapt_install/index.rst
- docs/source/chapt_install/install_python.rst
- pyproject.toml
- requirements-dev.txt
- setup.py
- Fix errors when running `pip install` on Windows
- Add version constraint for `setuptools<58` so that `build_py_2to3` is still available
> Ensure setuptools version compatible with adodbapi is installed

- docs/source/conf.py
- Recently, test runs have been failing due to Sphinx documentation build errors:
`14 WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).`
`15 make: *** [Makefile:242: dummy] Error 1`
`16 Error: Process completed with exit code 2.`
- The first warning is related to Sphinx Issue #10474 and PR #10481 where None was removed as a supported flag for the `language` entry. This update switches the flag to 'en' (the new default) to remove the warning.
-
-
1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this …
> Sphinx Documentation Build Issue

- requirements-dev.txt
- Recently, `pytest-qt` removed support for the package `py` which broke our CI runs
- This re-pins the package from 4.0.* to 4.2.* to resolve the issue
> Update `pytest-qt` to resolve `ModuleNotFoundError:`

- foqus_lib/gui/uq/uqSetupFrame.py
> Bad module path

- foqus_lib/conftest.py
- [`pytest.importorskip("my_module")`](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-importorskip) causes tests to be skipped if `my_module` can't be imported
- This is used in FOQUS to account for tests that require optional dependencies such as `tensorflow`
- However, because of a subtlety of its implementation (basically it raises a special exception), if `pytest.importorskip()` is used within a session-scoped fixture (as opposed to inside a test function, or at the top of a test module e.g. `test_my_optional_feature.py`), it will cause *all* tests to be skipped since session-scoped fixture functions are run before any other fixture or test
- Remove calls to `pytest.importorskip()` from session-scoped fixtures
- In our GitHub Actions workflow, the optional …
> Remove calls to pytest.importorskip() from session-scoped fixtures

- .pre-commit-config.yaml
- docs/source/chapt_dev/index.rst
- requirements-dev.txt
The `pre-commit` framework allows to specify arbitrary checks to be run automatically "client-side" whenever `git commit` is executed. This is especially useful to format the code automatically before it's even pushed to the FOQUS GitHub repository.
- Add `pre-commit` config file
- For the moment, the only enabled check is `black` code formatting
- Specify `pre-commit` as a dev dependency
- Add text about pre-commit checks in the developer section of the Sphinx docs
2. I represent I am authorized to make the contributions and grant the …
> Add pre-commit configuration

- foqus_lib/framework/sdoe/test/test_plot_utils.py
Added tests for plot_utils.py using mocking for matplotlib.pyplot
> Add test file for SDoE plot_utils.py

- foqus_lib/framework/session/session.py
Sets default location for psuade executable if found in the environment
> Set psuade default location with shutil

- docs/source/conf.py
Sphinx 6.2 introduced a deprecation for the format we have been using for `intersphinx_mapping` in `conf.py` (see https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping, "Old format for this config value"). This, in turn, causes the "Build Sphinx docs" CI job to fail.
- Update `intersphinx_mapping` to use the non-deprecated version.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these …
> Update intersphinx_mapping to non-deprecated format

- .github/workflows/checks.yml
- .github/workflows/nightlies.yml
- CI failures due to `macos-10.15` runners being unavailable, most likely because that version is outdated
> Update macOS GHA runner image to macos-12

- foqus_lib/framework/uq/SampleData.py
(replace this with the issue # fixed or addressed, if no issue exists then a brief statement of what this PR does)
- Add an `isinstance()` check before comparing with empty string to avoid NumPy error
> Resolve test failures due to NumPy 1.25

- docs/source/chapt_install/index.rst
- docs/source/chapt_install/install_foqus.rst
- setup.py
#1100
Allows users of MacOs on Apple silicon to install and run FOQUS.
- update to setup.py to exclude PyQt5 install on these machines
- documentation of steps required to install on these machines (once we have the next release out we can remove the need to download source as part of this)
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the …
> Changes to allow install for arm64 darwin.

- .readthedocs.yaml
- Add `build.os` and `build.tools` section to `.readthedocs.yaml`
> Add new mandatory sections to ReadTheDocs configuration

- docs/source/chapt_install/install_optional.rst
https://github.com/CCSI-Toolset/FOQUS/issues/1174
NLOpt isn't in psuade-lite:1.9 
but documentation claims it is.
-
-
> Add NLOpt installation instructions back

- docs/source/_repopath.py
- docs/source/chapt_HI/tutorial/HI_test.rst
- docs/source/chapt_flowsheet/tutorial/data.rst
- docs/source/chapt_flowsheet/tutorial/recycle.rst
- docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst
- docs/source/chapt_flowsheet/tutorial/simple_flowsheet.rst
- docs/source/chapt_idaes/tutorial/idaes_test.rst
- docs/source/chapt_odoe/tutorials.rst
- docs/source/chapt_opt/tutorial/simple.rst
- docs/source/chapt_ouu/tutorial.rst
- docs/source/chapt_pyomo/tutorial/pyomo_test.rst
- docs/source/chapt_sdoe/examples.rst
- docs/source/chapt_sinter/tutorial/acm.rst
- docs/source/chapt_sinter/tutorial/ap.rst
- docs/source/chapt_sinter/tutorial/excel.rst
- docs/source/chapt_sinter/tutorial/gproms.rst
- docs/source/chapt_sm_optimizer/tutorial/SM_based_optimizer_tutorial.rst
- docs/source/chapt_surrogates/tutorial/acosso.rst
- docs/source/chapt_surrogates/tutorial/alamo.rst
- docs/source/chapt_surrogates/tutorial/bssanova.rst
- docs/source/chapt_surrogates/tutorial/neural_networks.rst
- docs/source/chapt_surrogates/tutorial/uq_model.rst
- docs/source/chapt_uq/tutorial/analysis.rst
- docs/source/chapt_uq/tutorial/data.rst
- docs/source/chapt_uq/tutorial/inf.rst
- docs/source/chapt_uq/tutorial/rs.rst
- docs/source/chapt_uq/tutorial/sim.rst
- docs/source/conf.py
- Add small Sphinx extension adding `:path:` and `:filename:` roles to display paths relative to repository root with validation (a warning is emitted if the referred path is not found during the build)
- Convert a subset of the (non-role) paths found in the docs to use the `:path:`/`:filename:` roles
- Fix non-existing paths until build passes
This is how it looks when non-existing paths are used:
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that …
> Ensure paths mentioned in Sphinx docs are valid

- docs/source/chapt_ouu/tutorial.rst
- foqus_lib/framework/session/session.py
Fixes issue #1186 
While testing the 3.20 release candidate, few repeated documentation typos were found. This PR addresses those errors.
- Substitute the word "objection" with the word "objective"
> OUU: Fixing documentation typo

- docs/source/chapt_install/install_optional.rst
update FOQUS documentation to include info on how to set paths for SimSinter and TurbineLite
#1190 
With version 3 of SimSinter and TurbineLite the applications were upgraded to 64-bit and thus their default installation paths changed. FOQUS default paths for these point to the 32-bit Windows default installation paths. 
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make …
> update FOQUS documentation to include info on how to set paths for SimSinter and TurbineLite

- docs/source/chapt_debug/index.rst
Adds information on Turbine Configuration file to debugging section of the FOQUS documentation.
> Add Turbine Configuration Section To Debugging Documentation

- foqus_lib/foqus.py
- foqus_lib/framework/sdoe/nusf.py
- foqus_lib/framework/sdoe/nusf_dask.py
- foqus_lib/framework/sdoe/sdoe.py
- foqus_lib/framework/sdoe/test/nusf_benchmark.py
- foqus_lib/framework/sdoe/test/test_nusf_dask.py
- foqus_lib/framework/sdoe/test/test_usf_dask.py
- foqus_lib/framework/sdoe/test/usf_benchmark.py
- foqus_lib/framework/sdoe/usf.py
- foqus_lib/framework/sdoe/usf_dask.py
- foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
- requirements-dev.txt
- setup.py
#1193 
In order to improve the performance of the USF and NUSF algorithms for SDoE we parallelize them utilizing Dask. 
We verify that the parallelized implementation provides the same result as the original algorithm with performance gain (USF 2.5x across platforms; NUSF 3.5x on Windows).
- parallelized USF and NUSF algorithms utilizing Dask
- FOQUS command line option to utilize Dask for SDoE algorithms
- update to using Generator for random numbers generation for USF and NUSF (from legacy RandomState generators)
- tests to verify that the parallelized implementation provides the same results as the original algorithm given the same random number sequence
- benchmark to measure performance of the parallelized implementation vs the original algorithm
By contributing to this software …
> parallelize USF and NUSF algorithms using Dask

- .addheader.yml
- .pylint/foqus_transform.py
- foqus_lib/help/html/license.html
- foqus_lib/version/version.template
Found a couple more files with the old copyright dates.  Also fixed usage example in `.addheader.yml` file
The copyright years in the help dialogs were still "2012 - 2021"
-
-
> A few more copyright year updates

- foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
- setup.py
- result plots of SDOE runs would fail to display in some cases, e.g. NUSF
- #1209 
Fix bugs that are present in RC as related to SDOE UX
- pin matplotlib between 3.6.0 and 3.7.5 (<3.6 doesn't have wheels for python 3.11 and 3.8 introduces the issue with the plotting of results)
- fix setValue that was missed previously
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make …
> Fixes for bugs related to SDOE in 3.21-rc

- .typos.toml
- foqus_lib/framework/graph/graph.py
- foqus_lib/framework/sdoe/irsf.py
- foqus_lib/framework/session/session.py
- foqus_lib/framework/surrogate/ALAMO.py
- foqus_lib/framework/surrogate/surrogate.py
- foqus_lib/gui/main/mainWindow.py
Fixes typos or updates known exceptions
> Fix typos from recent update to v1.20.7

- foqus_lib/foqus.py
- Avoid situations where PSUADE not being available causes unclear error states
- Add check for PSUADE executable at FOQUS startup; if not found, exit immediately and display a link to FOQUS documentation
- Add CLI flag to specify a different PSUADE path, if needed
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of …
> Add check to ensure PSUADE is found at FOQUS startup

- .github/workflows/checks.yml
Codecov upload failures
- Use dedicated dependent job for Codecov upload (so that, in case of failure, only that job needs to be restarted, as opposed to the test suite that generated the coverage report)
- Update Action to `codecov/codecov-action@v4`
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that …
> Update Codecov CI configuration

- foqus_lib/framework/optimizer/PSUADE.py
- foqus_lib/framework/session/session.py
- foqus_lib/framework/surrogate/ALAMO.py
Corrects some new typos flagged by the spell checker.
> Fix Newly Flagged Typos

- foqus_lib/framework/graph/nodeVars.py
- foqus_lib/unit_test/nodeVars_test.py
Corrects unscaling formula for "Log" scaling formulation.
- Fix "Log" unscaling formula
- Updates tests to avoid false successes due to `self.min` having a value of 1 or 0
> Fix "Log" Scaling

- foqus_lib/framework/surrogate/ACOSSO.py
- foqus_lib/framework/surrogate/BSS-ANOVA.py
- foqus_lib/gui/flowsheet/nodePanel.py
- foqus_lib/gui/flowsheet/nodePanel_UI.ui
It addresses issue #1199
Sometimes the user might want to modify the timeout parameters in Aspen. Instead of making the user to go and modify an XML file, this panel helps them just type in a number and FOQUS will update the configuration file with the click of a button.
- added  tab to the node panel with a table that gets populated with the current values in the configuration file.
- added logic so the user can modify the values and the file gets updated correctly
2. I represent I am authorized to make the contributions and grant the …
> Adding Aspen Consumer Configuration Panel

- .github/workflows/checks.yml
- .github/workflows/nightlies.yml
- foqus_lib/framework/graph/graph.py
Github no longer supports windows-2019 per:  https://github.com/actions/runner-images/issues/12045
Get the nightlies running again
- Change windows-2019 to windows-2022
-
> Fix nightlies to build with windows-2022
